### ISSUE TITLE
SVD view : Write-only register bits cannot perform write operations

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-embedded-tools#19]
![image](https://user-images.githubusercontent.com/25566498/187646735-e023bd7c-8ca6-4966-921f-112a9d58c8cd.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Could you provide some more information about the situation where this occurred so that we can repro? 

For example, was the debugger in a paused state when this occurred?

**Comment by hongshui3000** [comment]
> For example, was the debugger in a paused state when this occurred?

yes，Only bit writes don't work (I click with the mouse, and a write box doesn't show up), the entire register at the top level is writable

**Comment by hongshui3000** [comment]
The read-write register can open the write interface
![image](https://user-images.githubusercontent.com/25566498/191260399-6252b306-247d-4fc9-abb6-01cf8984d095.png)
write-only register, I still can't open the bit write interface here
![image](https://user-images.githubusercontent.com/25566498/191260965-95289436-2bdf-47e7-a191-b0ba1a21a01c.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Correct, this is by design and by nature. 

Bit writes are performed by reading the register value, modifying it, and writing. Due to that, bit writes (also known as field writes), can only be performed on read-write registers. 

Notice that there are no permissions listed beside the bit that you attempted to write. This is because that bit (aka. `field`) is not writable.

**Comment by benmcmorran** [comment]
The change to the UI is now available in version 0.4.0 of the extension, which was released earlier today to the VS Code Marketplace.
