### ISSUE TITLE
Extension can't find static library

### ISSUE THREAD

**Issue by MatTab3335** [microsoft/vscode-embedded-tools#40]
Type: Bug Report

**Describe the bug**
- OS and Version - Windows 10:
- VS Code Version - 1.76.0:
- Embedded Tools Extension Version - v0.6.0:
- Target embedded device - STM32F405:

Hello! At the final make step:
`[build] [50/50] Linking C executable prj_upm_01.elf`

I get an error:
```
[build] FAILED: prj_upm_01.elf
....
[build] arm-none-eabi-gcc.exe: error: ../../libSTM32F4XX.a: No such file or directory
[build] arm-none-eabi-gcc.exe: error: ../../libkernel_m4f.a: No such file or directory
[build] arm-none-eabi-gcc.exe: error: ../../libmodbus_rtu_m4f.a: No such file or directory
[build] arm-none-eabi-gcc.exe: error: ../../libuip_m4f.a: No such file or directory
[build] arm-none-eabi-gcc.exe: error: ../../libIQmathLib-cm4f.a: No such file or directory
[proc] The command: c:\Users\Ivan\AppData\Roaming\Code\User\globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root\downloads\artifacts\vcpkg-ce-default\tools.kitware.cmake\3.20.1\bin\cmake.EXE --build C:/mexbiosdevelopmentstudio_ll_stm32cubeide/.../Libraries/STM32F4XX/prj_upm_01/build/debug/build --target prj_upm_01 exited with code: 1
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```
Project in Cube IDE makes fine, somehow extension can't find those static libs. Any ideas?

Cproject file in attachments (I couldn't download .cproject, so it in txt format)

[cproject.txt](https://github.com/microsoft/vscode-embedded-tools/files/10906283/cproject.txt)

**Comment by benmcmorran** [comment]
Thanks for the report. In the `.cproject` file the paths are simply specified as "other flags" for the linker, which is why the importer isn't attempting to do any special path translation.

Are the static libraries still being built in VS Code (probably to some other directory), or are they missing completely? If they're still being built, then it should be possible to modify the generated CMake script to point at the correct location.
