### ISSUE TITLE
Loading Problem on WSL

### ISSUE THREAD

**Issue by burakenez** [microsoft/vscode-embedded-tools#47]
Maybe It is only me or I am doing something wrong but while I am trying to open STM32 VS Code Extention, I am getting following error:

_Cannot activate the 'STM32 VS Code Extension' extension because it depends on the 'Embedded Tools' extension, which is not loaded. Would you like to reload the window to load the extension?_

Reloading did not solved the problem.

Extentions are working without problem at local. Having trouble on WSL only.

I checked that embedded tools extension is installed in wsl and it is enabled.

I couldn't find any info about wsl support at market place or at any documentation. Maybe this extention is not wsl supported.

Can you please help me how to make it work on WSL?

**Comment by benmcmorran** [comment]
I think this is actually an issue with the STM32 extension. It supports running either locally or remotely, but prefers to run locally even in remote scenarios, which is why there are errors loading the Embedded Tools extension. Can you try adding this snippet to your `settings.json` to force the STM32 extension to run remotely?

```json
  "remote.extensionKind": {
    "stmicroelectronics.stm32-vscode-extension": [
      "workspace"
    ]
  }
```

**Comment by burakenez** [comment]
Perfect. It is working now. Thanks.
