### ISSUE TITLE
How to work with JLinkGDBServer?

### ISSUE THREAD

**Issue by dsyx** [microsoft/vscode-embedded-tools#5]
I didn't find a detailed usage of the tool. But I found a configuration using OpenOCD in issues #3. I tried modifying the configuration to use JLinkGDBServer and the tool seems to work, but I can't control the debug operation.

```json
{
    "name": "Launch",
    "type": "cppdbg",
    "request": "launch",
    "program": "${workspaceFolder}/build/demo743.elf",
    "cwd": "${workspaceFolder}",
    "MIMode": "gdb",
    "miDebuggerPath": "C:/GNU Tools Arm Embedded/7 2018-q2-update/bin/arm-none-eabi-gdb.exe",
    "miDebuggerServerAddress": "localhost:2331",
    "debugServerPath": "C:/Program Files (x86)/SEGGER/JLink/JLinkGDBServerCL.exe",
    "debugServerArgs": "-if SWD -device STM32H743II",
    "svdPath": "${workspaceFolder}/STM32H743x.svd",
    "stopAtConnect": true
}
```

Can you tell me if the tool does not support JLinkGDBServer or how should I modify the configuration?

Thanks!

**Comment by aleun** [comment]
We've authored a JLinkGDBServer configuration for the NXP MIMXRT1060-EVK as part of the Azure RTOS Getting Started Guides. Can you take a look at [the "Launch" debug configuration](https://github.com/azure-rtos/getting-started/blob/c913de75a9552d8c1ea29c93c87f0628d7387742/NXP/MIMXRT1060-EVK/.vscode/launch.json#L25-L52) and see if that can be adapted for your purposes?

**Comment by dsyx** [comment]
Thanks for your answer, now the tool is working properly. @aleun

**Comment by cburlacu** [comment]
@aleun Can you allow only attaching to an already running debugging server (gdbserver, JLinkGDBServer, openocd, etc)?

**Comment by gcampbell-msft** [comment]
@cburlacu Yes! While there may be limitations to doing it that way, you should be able to attach to an already running debug server. To do this, you can simply remove the following fields from the json object:

- `debugServerPath`
- `debugServerArgs`
- `serverStarted`
- `preLaunchTask`
   - Note: This is because the current `preLaunchTask` depends on an openocd task that flashes the board, which won't work because there is already an openocd instance issue ready. 

This will then be able to attach to a running debug server.
